### PR TITLE
[#165715568] Add Concourse task definition for tests

### PR DESCRIPTION
**Pull request by AP-Hunt**
What
--
We have a template test pipeline for other repositories in `paas-release-ci` which will execute a Concourse task file at `ci/integration.yml`. This commit adds that task, so that tests can be run quickly on Concourse, rather than slowly on Travis.

`.travis.yml` is removed.

How to review
---
1. Code review

Who can review
---
Anyone

### CODE REVIEW

**Comment by tlwr** [comment]
```
...
env:
  GO111MODULE=on
...
run:
  dir: repo
  path: sh
  args:
    - -c
    - |
    set -eu
    go get
    make test
```

perhaps?

**Comment by AP-Hunt** [comment]
I think it would need to be `go get -t ./..` for the tests to run, but otherwise yeah lgtm. Will alter.

**Comment by tlwr** [comment]
`go get` using `go.mod` and `go.sum` should be enough as the test dependencies are recorded there.

**Comment by AP-Hunt** [comment]
> `go get` using `go.mod` and `go.sum` should be enough as the test dependencies are recorded there.

Aha, OK. I'll make that change.

**Comment by tlwr** [comment]
In fact we only need `make test`
```
...
env:
  GO111MODULE=on
...
run:
  dir: repo
  path: make
  args:
    - test
```

**Comment by AP-Hunt** [comment]
> In fact we only need `make test`
> 
> ```
> ...
> env:
>   GO111MODULE=on
> ...
> run:
>   dir: repo
>   path: make
>   args:
>     - test
> ```

Caught me before I could push the first change. Pushing that instead.

**Review by tlwr — APPROVED** [review]

**Pull request merged**
